apiVersion: apps/v1
kind: Deployment
metadata:
  name:  monitax
  namespace: default
  labels:
    app:  monitax
spec:
  selector:
    matchLabels:
      app: monitax
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  monitax
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  monitax
        image:  localhost:32000/monitax:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: SECRET_KEY
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: ENVIRONMENT
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: ACCESS_TOKEN_EXPIRE_MINUTES
        - name: REFRESH_TOKEN_EXPIRE_MINUTES
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: REFRESH_TOKEN_EXPIRE_MINUTES
        - name: BACKEND_CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: BACKEND_CORS_ORIGINS
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: ALLOWED_HOSTS
        - name: SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: SERVER_HOST
        - name: DEFAULT_DATABASE_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: DEFAULT_DATABASE_HOSTNAME
        - name: DEFAULT_DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: DEFAULT_DATABASE_USER
        - name: DEFAULT_DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: DEFAULT_DATABASE_PASSWORD
        - name: DEFAULT_DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: DEFAULT_DATABASE_PORT
        - name: DEFAULT_DATABASE_DB
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: DEFAULT_DATABASE_DB
        - name: SMTP_TLS
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: SMTP_TLS
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: SMTP_PORT
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: SMTP_HOST
        - name: SMTP_USER
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: SMTP_USER
        - name: SMTP_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: SMTP_PASSWORD
        - name: EMAILS_FROM_EMAIL
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: EMAILS_FROM_EMAIL
        - name: EMAILS_FROM_NAME
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: EMAILS_FROM_NAME
        - name: EMAIL_RESET_TOKEN_EXPIRE_HOURS
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: EMAIL_RESET_TOKEN_EXPIRE_HOURS
        - name: EMAIL_TEMPLATES_DIR
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: EMAIL_TEMPLATES_DIR
        - name: EMAILS_ENABLED
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: EMAILS_ENABLED
        - name: FIRST_SUPERUSER_EMAIL
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: FIRST_SUPERUSER_EMAIL
        - name: FIRST_SUPERUSER_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: monitax-config
              key: FIRST_SUPERUSER_PASSWORD
        ports:
        - containerPort:  8000
          name:  monitax
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Jakarta            
      restartPolicy: Always