"""User: add verified attribute

Revision ID: 9ae541a7d248
Revises: a7f02e95260d
Create Date: 2022-07-25 11:29:41.978549

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9ae541a7d248"
down_revision = "a7f02e95260d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column("device", "id", existing_type=postgresql.UUID(), nullable=True)
    # op.alter_column("invoice", "id", existing_type=postgresql.UUID(), nullable=True)
    op.add_column("user", sa.Column("verified", sa.Boolean(), nullable=True))
    # op.alter_column("user", "id", existing_type=postgresql.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "id", existing_type=postgresql.UUID(), nullable=False)
    op.drop_column("user", "verified")
    op.alter_column("invoice", "id", existing_type=postgresql.UUID(), nullable=False)
    op.alter_column("device", "id", existing_type=postgresql.UUID(), nullable=False)
    # ### end Alembic commands ###
