"""User: verified field=> default=False

Revision ID: 5a8df7bfecfb
Revises: 9ae541a7d248
Create Date: 2022-07-25 11:43:54.319973

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5a8df7bfecfb"
down_revision = "9ae541a7d248"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("device", "id", existing_type=postgresql.UUID(), nullable=True)
    op.alter_column("invoice", "id", existing_type=postgresql.UUID(), nullable=True)
    op.alter_column("user", "id", existing_type=postgresql.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "id", existing_type=postgresql.UUID(), nullable=False)
    op.alter_column("invoice", "id", existing_type=postgresql.UUID(), nullable=False)
    op.alter_column("device", "id", existing_type=postgresql.UUID(), nullable=False)
    # ### end Alembic commands ###
