"""add attribute phone_no

Revision ID: 83c1e7b8fc9a
Revises: 3abf0c596980
Create Date: 2022-07-09 17:41:46.820287

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "83c1e7b8fc9a"
down_revision = "3abf0c596980"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column("device", "id", existing_type=postgresql.UUID(), nullable=True)
    # op.alter_column("invoice", "id", existing_type=postgresql.UUID(), nullable=True)
    op.add_column(
        "user", sa.Column("phone_no", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # op.alter_column("user", "id", existing_type=postgresql.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "id", existing_type=postgresql.UUID(), nullable=False)
    op.drop_column("user", "phone_no")
    op.alter_column("invoice", "id", existing_type=postgresql.UUID(), nullable=False)
    op.alter_column("device", "id", existing_type=postgresql.UUID(), nullable=False)
    # ### end Alembic commands ###
